### ISSUE TITLE
It crashes when right-clicking on the empty space that is not a mod.

### ISSUE THREAD

**Issue by robojumper** [aEnigmatic/xcom2-launcher#1]
In MainForm.ModList.cs, line 328, it checks whether
`if (m.ID == null)`
but it should check
`if (m == null || m.ID == null)`
because `m` is `null` if we don't select a mod and as such, `m.ID` throws a `NullPointerException`. I would have checked if that fixes it but i can't get it to compile (errors in assigning the properties and stuff).

**Comment by aEnigmatic** [comment]
Thanks, that did indeed fix it. What are your problems with compiling?

**Comment by robojumper** [comment]
`public int Index { get; set; } = -1;`
Invalid token '=' (CS1519)
`public ModState State { get; set; } = ModState.None;`
Invalid token ';' (CS1519)
`public List<ModEntry> Entries { get; set; } = new List<ModEntry>();`
Invalid token '(' (CS1519)
`MessageBox.Show($"A mod could not...");`
Unexpected character '$' (CS1056)
`public ModList Mods { get; set; } = new ModList();`
Method must have a return type (CS1520)
Mostly these five
Am I missing any assemblies or using-directives? I don't get any errors regarding this, it's just the compiler errors above.

**Comment by BlueRaja** [comment]
Those are all new C# 6 syntax.  You need Visual Studio 2015 to compile it.

**Comment by robojumper** [comment]
Thank you. Makes sense, I really shouldn't be using SharpDevelop for stuff like this.

**Comment by BlueRaja** [comment]
There's no reason to use SharpDevelop _(on Windows at least)_, VS 2015 is free: https://www.visualstudio.com/products/visual-studio-community-vs

**Comment by robojumper** [comment]
free*

*If Microsoft hadn't locked me out of my account. But the crash is fixed, so whatever.
