### ISSUE TITLE
Can't load two mods that show as conflicting (But it's a false positive)

### ISSUE THREAD

**Issue by ChaoticTabris** [aEnigmatic/xcom2-launcher#10]
I've got "Grimy's Loot Mod" and it's requirement "Mod Everything". The Mod Launcher shows them as conflicting even though they have code to account for both mods editing the same entry. I was able to use them fine until the last update (0.4.2), now when i try to load my save it says both mods are missing. Did anything stopping mods that are seen by the launcher as conflicting was added on the last update? Both mods are checked on the launcher.

**Comment by aEnigmatic** [comment]
I fixed that just now, my bad :)

Will see if I can do anything about those two being marked in the first place...

**Comment by ChaoticTabris** [comment]
Wow! That was fast!
Thanks :)
