### ISSUE TITLE
Feature request/query

### ISSUE THREAD

**Issue by Plockets** [aEnigmatic/xcom2-launcher#11]
Is there a way to add launch options? For example, -allowconsole is pretty big deal to many, including myself, I really want my Fogdensity = 0!

Ideally, this launcher would default to using the same launch options Steam does, although I have no idea if that is easily accomplished or not.

**Comment by aEnigmatic** [comment]
Did you try `Settings > Edit`? ;)

**Comment by Plockets** [comment]
Aha, thanks!
