### ISSUE TITLE
"An exception occurred. See error.log for additional details."

### ISSUE THREAD

**Issue by Powerlevel9001** [aEnigmatic/xcom2-launcher#18]
I cannot open the Mod Launcher suddenly, with the above error given. Opening error.log, I received this message:

Object reference not set to an instance of an object.
Stack:
   at XCOM2Launcher.Program.InitializeSettings()
   at XCOM2Launcher.Program.Main()

I'm not quite sure what caused this, any ideas?

**Comment by colekern** [comment]
Your config most likely got deleted somehow. All you have to do to fix this launch the game with the vanilla launcher through steam. You don't even have to go into your save file, just open the game to the main menu. After that the mod launcher will work just fine. 
If this isn't the issue, try deleting the config manually then doing what I wrote above.
