### ISSUE TITLE
Unhandled Exception when launching

### ISSUE THREAD

**Issue by ZerggedTrem** [aEnigmatic/xcom2-launcher#19]
Just installed this amazing tool, it worked the first few times I launched. Then something borked, verified game cache, then that borked another thing. Now it is spitting out a long Unhandled Exception error, attachement .txt #1.

Currently using these mods .txt #2. Credit to soup specialist over on reddit, he's a cool dude for putting the list together for me.

[Unhandled Issue 1.txt](https://github.com/aEnigmatic/xcom2-launcher/files/635493/Unhandled.Issue.1.txt)
[Unhandled Issue 2, soup specialist.txt](https://github.com/aEnigmatic/xcom2-launcher/files/635492/Unhandled.Issue.2.soup.specialist.txt)

**Comment by aEnigmatic** [comment]
It seems the game path is wrong. Try changing it via the settings menu and see if that helps

**Comment by ZerggedTrem** [comment]
That did it, thank you!
