### ISSUE TITLE
Add Changelog tab in the informations pane

### ISSUE THREAD

**Issue by Anahkiasen** [aEnigmatic/xcom2-launcher#2]
Currently the manager tells you whether a mod has been updated recently, it would be nice if you could also peek at the changelog see what the change was. Talking about the information [found here](http://steamcommunity.com/sharedfiles/filedetails/changelog/618977388).

I don't know if those informations are available through the API, if not this can probably be closed.

**Comment by aEnigmatic** [comment]
Sadly, neither the steam nor the web API have an interface for that data.
I might add a link, though.

**Comment by robojumper** [comment]
You could extract the changelog via a WebClient and RegEx if you wanted to. I tried a little bit around, it's up to you whether you want it. 
![x2modlauncher](https://cloud.githubusercontent.com/assets/14299449/13994338/98874d7c-f124-11e5-8408-f945e02061c7.png)
[Just checkout my fork](https://github.com/robojumper/xcom2-launcher). Beware, I am a noob with Git(Hub) and i may have borked things.

**Comment by Anahkiasen** [comment]
That would be good enough for me in my book, not sure what the Steam license says about crawling though.

**Comment by BlueRaja** [comment]
@robojumper Click the 'code' button above, then 'Create Pull Request'.  Then we can do a code review of the code, and the repo-owner can automatically merge your code when it looks good.
